### ISSUE TITLE
Ошибка в консоли

### ISSUE THREAD

**Issue by voron5096** [doterurod/ArmyAutosolverPublic#4]
@doterurod 
![image](https://user-images.githubusercontent.com/70198995/119651365-9c4c8b80-be2d-11eb-9418-e9da371a030c.png)

**Comment by voron5096** [comment]
UPDATE: Оказывается один тест уже был решён, и поэтому программа не может его заново решить. Не знаю как это исправить, буду думать

**Comment by Lesterrry** [comment]
У меня такое было, я поправил

**Comment by Lesterrry** [comment]
```
try:
json_data = r.json()['data']        except:            print("Тест непроходим")            return
```

**Comment by lesterrry** [comment]
Вставьте вместо строки 42 и все
```
try:
    json_data = r.json()['data']
except:
    print("Тест непроходим")
    return
```

**Comment by lesterrry** [comment]
и вообще можете [мою вилку](https://github.com/Lesterrry/ArmyAutosolverPublic/blob/main/solver.py) чекнуть, я там всяких штук помимо этой дописал

**Comment by voron5096** [comment]
> 
> 
> и вообще можете [мою вилку](https://github.com/Lesterrry/ArmyAutosolverPublic/blob/main/solver.py) чекнуть, я там всяких штук помимо этой дописал

спасибо, а то я бы замучился дописывать это самостоятельно :)
